# Site settings
title: Ethan made
tagline: Art mostly
email: ethan@leemiller.email
description: > # this means to ignore newlines until "baseurl"
  Random things I'm making
baseurl: "/made/" # the subpath of your site, e.g. /blog/
url: "http://ethanmiller.name" # the base hostname & protocol for your site
twitter_username: ethanmiller
github_username:  ethanmiller
paginate: 5

# Build settings
markdown: kramdown
highlighter: pygments
sass:
    style: :compressed

# Gems
gems: [jekyll-paginate]
